## **Numpy: Basic numerical operation. Matrix operation plus some basic solvers.**

In [3]:
import numpy as np

In [4]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [6]:
# v = np.array([1, 2]).reshape((2, 1))
v = np.array([1, 2])
v

array([1, 2])

In [7]:
np.dot(X, v) # no broadcasting

array([ 5, 11])

In [8]:
X * v # broadcasting

array([[1, 4],
       [3, 8]])

In [9]:
np.dot(v, X)

array([ 7, 10])

In [10]:
X - X.mean(axis=0)

array([[-1., -1.],
       [ 1.,  1.]])